Upgrade version of @openzeppelin/hardhat-upgrades to 1.20.0
The version seems to be solving problems with contracts verification we
were experiencing:
```
Error: ERROR processing /Users/jakub/go/src/github.com/keep-network/keep-core/solidity/ecdsa/deploy/03_deploy_wallet_registry.ts:
NomicLabsHardhatPluginError: The contract you want to verify was compiled with solidity 0.8.2, but your configured compiler versions are: 0.8.9, 0.8.9.
```