Add empty files in _address folders to prevent from failing compilation
When `go make` was run without earlier running `go generate` (which is how `go
vet` and staticcheck` tools work), we were getting following complaints:
```
Error: pkg/chain/ethereum/beacon/gen/gen.go:11:13: pattern _address/RandomBeacon: no matching files found
Error: pkg/chain/ethereum/ecdsa/gen/gen.go:11:13: pattern _address/WalletRegistry: no matching files found
Error: pkg/chain/ethereum/threshold/gen/gen.go:11:13: pattern _address/TokenStaking: no matching files found
```
This was because the `_address/RandomBeacon`, `_address/WalletRegistry` and
`_address/TokenStaking` files were not in the repository (they are generated and
populated as a result of `go generate`). To avoid getting failures repported by
`go vet` and `staticcheck` we decided to create emplty placeholder files.